add modal windows
MaksimVladimirov/js_project pull request #3
Opened 2022-12-09 10:28 UTC by MaksimVladimirov

Добавил модальные окна

2022-12-09 16:04 UTC, andrey-kudinov requested changes
Хорошая работа
Есть несколько моментов, которые можно улучшить
Посмотри пж в комментариях

2022-12-09 16:54 UTC, MaksimVladimirov commented on src/js/modules/modals.js
> +            modal = document.querySelector(modalSelector),
Исправил

2022-12-09 16:56 UTC, MaksimVladimirov commented on src/js/modules/modals.js
> +            modal = document.querySelector(modalSelector),
исправил

2022-12-10 15:27 UTC, andrey-kudinov commented on src/js/modules/tabs.js
> +tabs({ headerSelector,
Я так понимаю функция tab должна вызываться не здесь, а в главном файле

2022-12-10 15:28 UTC, andrey-kudinov commented on src/js/main.js
> +  tabs(".glazing_slider ", ".glazing_block", ".glazing_content", "active");
Обрати внимание, что здесь ты уже должен передать функции объект

2022-12-10 18:06 UTC, andrey-kudinov commented on src/js/main.js
> +    headerSelector: ".glazing_slider ",
Лишний пробел

2022-12-10 18:16 UTC, merged